URL_SERVICE = "https://cnt-95a97243-a26e-49ee-8276-b98de8f67a67.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"